NET ASP Core MVC/InlandMarina/Controllers/SlipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InlandMarinaData;

namespace InlandMarina.Controllers
{
    public class SlipsController : Controller
    {
        private readonly InlandMarinaContext _context;

        public SlipsController(InlandMarinaContext context)
        {
            _context = context;
        }

        // For /Slips
        public IActionResult Index(int id = 1, int filter = 0)
        {
            var inlandMarinaContext = _context.Slips.Include(s => s.Dock).Include(s => s.Leases).Where(s => s.DockID == id);

            var numDocks = _context.Docks.Count();

            if (filter == 1)
            {
               inlandMarinaContext = inlandMarinaContext.OrderByDescending(s => s.Length);
            }
            else if (filter == 2)
            {
                inlandMarinaContext = inlandMarinaContext.OrderBy(s => s.Length);
            }
            else if (filter == 3)
            {
                inlandMarinaContext = inlandMarinaContext.OrderByDescending(s => s.Width);
            }
            else if (filter == 4)
            {
                inlandMarinaContext = inlandMarinaContext.OrderBy(s => s.Width);
            }

            ViewBag.DockID = id;
            ViewBag.CurrentFilter = filter;
            ViewBag.numDocks = numDocks;

            List<Slip> availableSlips = new List<Slip>();
            foreach (var item in inlandMarinaContext.ToList())
            {
                if (item.isAvailable)
                {
                    availableSlips.Add(item);
                }
            }

            return View(!User.IsInRole("Admin") ? availableSlips: inlandMarinaContext.ToList());
        }

        // For Slips/Details/{id}
        public async Task<IActionResult> Details(int? id)
        {
            if (!User.Identity.IsAuthenticated) return RedirectToAction("Index", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var slip = await _context.Slips
                .Include(s => s.Dock)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (slip == null)
            {
                return NotFound();
            }

            return View(slip);
        }

        public IActionResult AddSlip(int? id)
        {
            if (!User.Identity.IsAuthenticated) return RedirectToAction("Index", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var slip = _context.Slips.Where(s => s.ID == id).FirstOrDefault();

            var user = _context.Customers.Where(u => u.Email == User.Identity.Name).FirstOrDefault();

            var lease = new Lease()
            {
                SlipID = slip.ID,
                CustomerID = user.Id,
                Customer = user,
                Slip = slip
            };

            _context.Leases.Add(lease);

            _context.SaveChanges();

            var addedLease = _context.Leases.Where(s => s.SlipID == lease.SlipID).FirstOrDefault();

            slip.Leases.Add(addedLease);

            _context.SaveChanges();

            return View();
        }

        private bool SlipExists(int id)
        {
            return _context.Slips.Any(e => e.ID == id);
        }
    }
}

NET ASP Core MVC/InlandMarina/Views/Slips/AddSlip.cshtml
@{
    ViewData["Title"] = "Confirmed";
}

<h1>Transaction confirmed</h1>
<p>You can now view the lease in "Your Leases"</p>
<a class="btn btn-primary" asp-area="Customer" asp-controller="Home" asp-action="Index">Your Leases</a>

NET ASP Core MVC/InlandMarina/Views/Slips/Details.cshtml
@model InlandMarinaData.Slip

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Slip</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Length)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Length)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dock.Name)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-controller="Slips" asp-action="AddSlip" asp-route-id="@Model.ID">Reserve</a>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

NET ASP Core MVC/InlandMarina/Views/Slips/Index.cshtml
@model IEnumerable<InlandMarinaData.Slip>

@{
    ViewData["Title"] = "Inland Marina - Slips";
}

    <div class="container row w-75 align-items-center filter-container">
        <h1 class="col">Slips</h1>
        <div class="custom-select col">
            <button class="select-button">Select Filter</button>
            <div class="select-options hidden">
            <a href="@Url.Action("Index", new { id = ViewBag.DockID, filter = 1 })" class="@(ViewBag.CurrentFilter == 1 ? "selected" : "")">Length Descending</a>
            <a href="@Url.Action("Index", new { id = ViewBag.DockID, filter = 2 })" class="@(ViewBag.CurrentFilter == 2 ? "selected" : "")">Length Ascending</a>
            <a href="@Url.Action("Index", new { id = ViewBag.DockID, filter = 3 })" class="@(ViewBag.CurrentFilter == 3 ? "selected" : "")">Width Descending</a>
            <a href="@Url.Action("Index", new { id = ViewBag.DockID, filter = 4 })" class="@(ViewBag.CurrentFilter == 4 ? "selected" : "")">Width Ascending</a>
            <a href="@Url.Action("Index", new { id = 1, filter = 5 })" class="@(ViewBag.CurrentFilter == 5 ? "selected" : "")">Dock 1</a>
            <a href="@Url.Action("Index", new { id = 2,filter = 6 })" class="@(ViewBag.CurrentFilter == 6 ? "selected" : "")">Dock 2</a>
            <a href="@Url.Action("Index", new { id = 3, filter = 7 })" class="@(ViewBag.CurrentFilter == 7 ? "selected" : "")">Dock 3</a>
            </div>
        </div>
    </div>
@{
    if (User.IsInRole("Admin"))
    {
        <a class="btn btn-primary btn-create col" href=Admin/Create/ >Create</a>
    }
}



<table>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dock)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Width) FT
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Length) FT
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dock.Name)
            </td>
            <td class="slips-buttons">
                @{
                  if (User.IsInRole("Admin"))
                  {
                      <a class="btn btn-primary" href=/Admin/Edit/@(item.ID)>Edit</a>
                      <a class="btn btn-danger" href=/Admin/Delete/@(item.ID)>Delete</a>
                  }
                  else
                  {
                      if (User.Identity.IsAuthenticated)
                      {
                       <a class="btn btn-primary" asp-controller="Slips" asp-action="Details" asp-route-id="@item.ID">Reserve</a>
                      }
                      else
                      {
                       <a class="btn btn-primary" asp-action="Login" asp-area="Identity" asp-controller="Account">Reserve</a>
                      }
                  } 
                 }
            </td>
        </tr>
}
    </tbody>
</table>

<ul class="pagination justify-content-center">    
    @for (var i = 0; i < ViewBag.numDocks; i++)
    {
        <li class="page-item"><a class="page-link" asp-action="Index" asp-route-id="@(i + 1)">@(i + 1)</a></li>
    }
</ul>

<script>
    const selectButton = document.querySelector('.select-button');
    const selectOptions = document.querySelector('.select-options');

    document.addEventListener('DOMContentLoaded', function () {
        selectButton.addEventListener('click', function () {
            selectOptions.classList.toggle('hidden');
        });
        selectOptions.style.width = `${selectButton.getBoundingClientRect().width}px`;
    });

    window.addEventListener("resize", function () {
        selectOptions.style.width = `${selectButton.getBoundingClientRect().width}px`;
    });
</script>